name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: |
        cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u stromhalm --password-stdin
        docker build . --file Dockerfile --tag docker.pkg.github.com/stromhalm/angular-apt:$(date +%s)
        docker push docker.pkg.github.com/stromhalm/angular-apt/IMAGE_NAME:VERSION
