name: Deploy Github Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo $GH_TOKEN | docker login docker.pkg.github.com -u stromhalm --password-stdin
        docker build . --file Dockerfile --tag docker.pkg.github.com/stromhalm/angular-apt/apt-docker:$(date +%s)
        docker push docker.pkg.github.com/stromhalm/angular-apt/apt-docker
